services:
  _defaults:
    autowire: true
    autoconfigure: true

  Selective\ArchiveBomb\Scanner\BombScanner: ~
  Ipedis\SecurityFileBundle\Service\BombScanner\BombScannerDecorator:
    decorates: Selective\ArchiveBomb\Scanner\BombScanner
    arguments:
      $bombScanner: '@.inner'
      $engines: '%scanner.engines%'
  Ipedis\SecurityFileBundle\Service\BombScanner\BombScannerInterface: '@Ipedis\SecurityFileBundle\Service\BombScanner\BombScannerDecorator'

  Ipedis\SecurityFileBundle\Service\Validator\FileValidator: ~
  Ipedis\SecurityFileBundle\Service\Validator\FileValidatorInterface: '@Ipedis\SecurityFileBundle\Service\Validator\FileValidator'
